[package]
name = "bitcoin-like-rust"
version = "0.1.0"
edition = "2021"

[workspace]
resolver = "2"
members = ["miner", "node", "wallet", "btclib"]

[dependencies]
btclib = { path = "./btclib" }
uuid = { version = "1.8.0", features = ["v4", "serde"] }
chrono = { version = "0.4.39", features = ["serde"] }
